@startuml blue-green-after

top to bottom direction


node "<<Load Balancer>>" as LB {
}

folder "Infraestrutura" as I {
  node "Servidor 2\n  Versão atual" as S2 #96C0FF {
    component "App" <<component>> { 
    }
  }
  node "Servidor 1\n  Versão atualizada" as S1 #81EB3B {
    component "App " <<component>> { 
    }
  }
}

..> LB 

LB ..> S1

@enduml
