@startuml dm

skinparam classAttributeIconSize 0
hide empty attributes
hide empty methods
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

left to right direction

entity "Classe" as c {
  - name
}

entity "SubClasse" as sc {
  - name
}

entity "Competição" as comp {
  - name
  - start_date
  - end_date 
}

entity "Evento" as e {
  - name
  - date
}

entity "Mercado" as m {
  - name
}

entity "Seleção" as s {
  - name
  - odd
}

c "1" --> "1..*" sc
sc "1" --> "*" comp
comp "1" --> "1..*" e
e "1" --> "1..*" m
m "1" --> "1..*" s

@enduml
