@startuml ucd

left to right direction

skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    ArrowColor DarkBlue
    FontStyle Bold
}

:Utilizador: as AE

left to right direction

rectangle "Use Cases" as uc {
  usecase "1. Consultar os eventos ativos num determinado dia." as UC1
  usecase "2. Consultar os tipos de aposta disponíveis para um determinado evento." as UC2
  usecase "3. Consultar as odds de um num determinado evento." as UC3
}

AE --> UC1
AE --> UC2
AE --> UC3 

@enduml

